# Generated by Django 4.0.5 on 2022-07-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dowell', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopulationFunction',
            new_name='Population',
        ),
    ]
